In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_weather = pd.read_csv("../data/raw/weather_data.csv")

In [2]:
df_weather.head()

         date  temp_avg  temp_min  temp_max  precipitation        country
0  2016-08-05      27.2      23.0      32.0            NaN  United States
1  2016-08-06      24.5      22.0      26.0            NaN  United States
2  2016-08-10      27.5      22.0      35.0            NaN  United States
3  2016-08-12      26.8      25.0      30.0            NaN  United States
4  2016-08-31      23.3      22.2      27.2            NaN  United States

In [3]:
df_weather.isnull().sum()

date               0
temp_avg           3
temp_min         114
temp_max           8
precipitation    457
country            0
dtype: int64

In [4]:
df_weather.shape

(1830, 6)

In [5]:
df_weather['country'].value_counts()

country
United States     366
Turkey            366
United Kingdom    366
Germany           366
Japan             366
Name: count, dtype: int64

In [6]:
df_weather.groupby('country')['precipitation'].mean()

country
Germany           1.372404
Japan             3.660055
Turkey                 NaN
United Kingdom    4.254098
United States     1.089568
Name: precipitation, dtype: float64

In [7]:
df_weather_turkey = df_weather[(df_weather['country']=='Turkey') & (df_weather['precipitation'] > 0)]

In [8]:
print(df_weather_turkey)

Empty DataFrame
Columns: [date, temp_avg, temp_min, temp_max, precipitation, country]
Index: []

In [9]:
df_weather = df_weather[df_weather['country'] != "Turkey"]

In [10]:
df_weather.head()

         date  temp_avg  temp_min  temp_max  precipitation        country
0  2016-08-05      27.2      23.0      32.0            NaN  United States
1  2016-08-06      24.5      22.0      26.0            NaN  United States
2  2016-08-10      27.5      22.0      35.0            NaN  United States
3  2016-08-12      26.8      25.0      30.0            NaN  United States
4  2016-08-31      23.3      22.2      27.2            NaN  United States

In [11]:
df_weather['country'].unique()

array(['United States', 'United Kingdom', 'Germany', 'Japan'],
      dtype=object)

In [12]:
df_weather.isnull().sum()

date               0
temp_avg           3
temp_min         113
temp_max           7
precipitation     91
country            0
dtype: int64

In [14]:
# Nan values were replaced with null values because the analysis is guided through extreme weather events
df_weather['precipitation'] = df_weather['precipitation'].fillna(0)

In [15]:
df_weather['temp_avg'] = df_weather['temp_avg'].fillna(df_weather['temp_avg'].mean())

In [16]:
df_weather['temp_min'] = df_weather['temp_min'].fillna(df_weather['temp_avg'])
df_weather['temp_max'] = df_weather['temp_max'].fillna(df_weather['temp_avg'])

In [17]:
df_weather.isnull().sum()

date             0
temp_avg         0
temp_min         0
temp_max         0
precipitation    0
country          0
dtype: int64

In [19]:
df_weather.dtypes

date              object
temp_avg         float64
temp_min         float64
temp_max         float64
precipitation    float64
country           object
dtype: object

In [18]:
df_weather.to_csv("../data/processed/weather_clean.csv", index=False)