In [1]:
import pandas as pd

In [5]:

df_mobile_broadband = pd.read_csv("../data/raw/active_mobile_broadband_subscriptions.csv")

In [6]:
df_mobile_broadband.head(10)

          Economy      2016      2017
0          Brazil   90.3983   92.2579
1          Canada   68.6924   71.8122
2         Germany   76.2383   78.8279
3           India   16.1730   25.3750
4           Japan  131.7320  134.5590
5        Thailand   90.2867   77.5420
6         Türkiye   63.3626   68.5390
7  United Kingdom   83.1381   87.7499
8   United States  124.3010  129.8740
9        Viet Nam   46.7223   47.1275

In [10]:
df_mobile_broadband["Economy"] = df_mobile_broadband["Economy"].replace({
    "Viet Nam": "Vietnam", "Türkiye": "Turkey"})

In [11]:
df_mobile_broadband.head(10)

          Economy      2016      2017
0          Brazil   90.3983   92.2579
1          Canada   68.6924   71.8122
2         Germany   76.2383   78.8279
3           India   16.1730   25.3750
4           Japan  131.7320  134.5590
5        Thailand   90.2867   77.5420
6          Turkey   63.3626   68.5390
7  United Kingdom   83.1381   87.7499
8   United States  124.3010  129.8740
9         Vietnam   46.7223   47.1275

In [13]:
df_mobile_broadband['mobile_broadband_subscriptions_per_100_people'] = df_mobile_broadband[['2016', '2017']].mean(axis=1)

In [14]:
df_mobile_broadband = df_mobile_broadband[['Economy', 'mobile_broadband_subscriptions_per_100_people']]
df_mobile_broadband.columns = ['country', 'mobile_broadband_subscriptions_per_100_people']

In [16]:
df_mobile_broadband.head(10)

          country  mobile_broadband_subscriptions_per_100_people
0          Brazil                                       91.32810
1          Canada                                       70.25230
2         Germany                                       77.53310
3           India                                       20.77400
4           Japan                                      133.14550
5        Thailand                                       83.91435
6          Turkey                                       65.95080
7  United Kingdom                                       85.44400
8   United States                                      127.08750
9         Vietnam                                       46.92490

In [17]:
df_mobile_broadband['mobile_broadband_subscriptions_per_100_people'] = (
    df_mobile_broadband['mobile_broadband_subscriptions_per_100_people'].round(2))

In [18]:
df_mobile_broadband.head()

   country  mobile_broadband_subscriptions_per_100_people
0   Brazil                                          91.33
1   Canada                                          70.25
2  Germany                                          77.53
3    India                                          20.77
4    Japan                                         133.15

In [ ]:
df_mobile_broadband.to_csv("../data/processed/mobile_broadband_clean.csv", index=False)

https://datahub.itu.int/query/